name    'opentable-etcd-v3'
version '1.0.0'
source 'https://github.com/opentable/puppet-etcd-v3'
author 'Chris Cartlidge, Robert Loung, Kyle Anderson'
license 'Apache License, Version 2.0'
summary 'A Puppet module to install and configure etcd v3.X'
description 'A Puppet module to install and configure etcd v3.X'
project_page 'https://github.com/opentable/puppet-etcd-v3'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
